### ISSUE TITLE
Endpoints with characters that are not allowed in Python

### ISSUE THREAD

**Issue by marksher** [kadirpekel/hammock#20]
I've run into an endpoint with a hyphen (-) in it, which wraps api.website/end-point/?querystring=xxxx into website.end-point('?querystring=xxxx').GET() and I'm getting errors when I try to access it that way.

This character is completely valid in the REST documentation.  I assume there are others, but this is the one that I came across.  I didn't see anything that handles this type of case in the source.

**Comment by kmarekspartz** [comment]
It's been a little while, but I think I would do `website('end-point')('?query_string=')(xxx).GET()`

**Comment by marksher** [comment]
Thanks for the tip!  I tried a few different combinations of ('end-point') in there, but couldn't get anything to run.  I'm doing some research on the quoting technique to see if there are other ways to go at this.  Best,  Mark.

**Comment by marksher** [comment]
Nevermind.  It worked!  My actual case was a bit more complicated than the example case I added, but it's all set now.  Thanks a lot for the quick reply and a helpful tip for the future.

**Comment by kotnik** [comment]
This needs to be documented, just had to re-invent it...
